### PR TITLE
Quickstart overhaul

### LINKED ISSUE #277: 1️⃣ Fix issues with Quickstart
- [ ] Grammatical and style issues
- [ ] Incorrect code examples
- [ ] Rework test code

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
## fixes #277 

Overhauls language, style, flow, and code issues with quickstart.

## How to test:

Run thorough the quickstart and hopefully have fully functioning code.

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [x] I have documented the changes (where applicable)
    * Either PR or Ticket to update [the Docs](https://github.com/KILTprotocol/docs)
    * Link the PR/Ticket here

### CODE REVIEW

File: code_examples/sdk_examples/src/core_features/did/11_full_did_delete.ts [hunk 1]
```diff
@@ -10,9 +10,8 @@ export async function deleteFullDid(
   // Create a DID deletion tx. We specify the number of endpoints currently stored under the DID because
   // of the upper computation limit required by the blockchain runtime.
   const didIdentifier = Kilt.Did.toChain(fullDid)
-  const endpointsCountForDid = await api.query.did.didEndpointsCount(
-    didIdentifier
-  )
+  const endpointsCountForDid =
+    await api.query.did.didEndpointsCount(didIdentifier)
```
Comment (Dudleyneedham) [inline code_examples/sdk_examples/src/core_features/did/11_full_did_delete.ts:14]: How come this isn't caught with the linting?

File: code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts [hunk 2]
```diff
@@ -10,6 +10,7 @@ export async function main(
   } = await axios.get<Kilt.KiltPublishedCredentialCollectionV1>(
     endpoints[0].serviceEndpoint[0]
   )
-
+  console.log('Credentials:')
+  console.log(credential)
```
Comment (Dudleyneedham) [inline code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts]:
```suggestion
  console.log(`Credentials: ${credential}`)
```

**Review by Dudleyneedham — CHANGES_REQUESTED** [review]
Minor comments. I'm not sure why this linting isn't catching these. Did you run `lint --fix`?

File: code_examples/sdk_examples/src/core_features/did/11_full_did_delete.ts (hunk 1 above)
Comment (ChrisChinchilla) [reply code_examples/sdk_examples/src/core_features/did/11_full_did_delete.ts:14]: @Dudleyneedham I did… But… I didn't actually intentionally change any of these files, and despite multiple actions runs (take a look) that asked me to run style and lint fixes on code that I also never touched, the tests all now show as passed and nothing identifies this particular issue 🤷 .

I'm actually not even sure what it's supposed to be?

Comment (Dudleyneedham) [reply code_examples/sdk_examples/src/core_features/did/11_full_did_delete.ts:14]: Ok fair enough.

File: docs/develop/01_sdk/01_quickstart.md [hunk 3]
```diff
@@ -18,131 +19,87 @@ import FetchEndpointData from '!!raw-loader!@site/code_examples/sdk_examples/src
...
+Begin by importing the **KILT SDK** and **Axios** at the top of the file:
 
 ```js
 import * as Kilt from '@kiltprotocol/sdk-js'
 import axios from 'axios'
 ```
 
-Now you are able to access the SDK and all its functionality.
-We will move onto connecting to the **KILT blockchain**.
+Now, you can access the SDK and all its functionality. The next step is connecting to the **KILT blockchain**.
```
Comment (Dudleyneedham) [inline docs/develop/01_sdk/01_quickstart.md]:
```suggestion
Now, you can access the SDK and all its functionality.
The next step is connecting to the **KILT blockchain**.
```

File: docs/develop/01_sdk/01_quickstart.md [hunk 4]
```diff
@@ -162,80 +119,102 @@ Within the same `main` function, configure the SDK to connect to a KILT node usi
   </TabItem>
 </Tabs>
 
-To ensure proper cleanup, call the `Kilt.disconnect()` function at the bottom of the main function:
+To ensure proper cleanup, call the `Kilt.disconnect()` function at the bottom of the `main()` function. You should add all other code before this function call:
```
Comment (Dudleyneedham) [inline docs/develop/01_sdk/01_quickstart.md]:
```suggestion
To ensure proper cleanup, call the `Kilt.disconnect()` function at the bottom of the `main()` function.
You should add all other code before this function call:
```

File: docs/develop/01_sdk/01_quickstart.md [hunk 5]
```diff
@@ -162,80 +119,102 @@ Within the same `main` function, configure the SDK to connect to a KILT node usi
...
 >
-  {Disconnect}
+{Disconnect} 
 </SnippetBlock>
 
-By adding `await Kilt.disconnect()` at the end of the main function, you ensure that the connection to the blockchain node is properly closed when the script finishes executing.
-This helps maintain the integrity of your application and is a good practice to follow.
+By adding `await Kilt.disconnect()`, you ensure that the connection to the blockchain node is properly closed when the script finishes executing, which helps maintain the integrity of your application and is a good practice to follow.
+
+Run the code by calling the name of the file. If you set up everything correctly, you should see no output showing that your code connected to the **KILT blockchain**.
```
Comment (Dudleyneedham) [inline docs/develop/01_sdk/01_quickstart.md]:
```suggestion
Run the code by calling the name of the file.
If you set up everything correctly, you should see no output showing that your code connected to the **KILT blockchain**.
```

File: docs/develop/01_sdk/01_quickstart.md [hunk 6]
```diff
@@ -162,80 +119,102 @@ Within the same `main` function, configure the SDK to connect to a KILT node usi
...
+</Tabs>
 
-Congratulations!
-You have connected to a KILT blockchain node.
-Let's now start querying some data from the chain!
+As you add to the code in this file, you can always run it with the same command.
+
+**Congratulations! 🔥**
+
+You have connected to a KILT blockchain node. The next step is to start querying data from the blockchain.
```
Comment (Dudleyneedham) [inline docs/develop/01_sdk/01_quickstart.md]:
```suggestion
You have connected to a KILT blockchain node.
The next step is to start querying data from the blockchain.
```

File: docs/develop/01_sdk/01_quickstart.md [hunk 7]
```diff
@@ -162,80 +119,102 @@ Within the same `main` function, configure the SDK to connect to a KILT node usi
...
-One type of external resource is represented by, you guessed it, **KILT credentials**!
-Therefore, let's see how we can retrieve the **services** of John Doe's DID and see if they link to any public credentials for us to **query** and **verify**.
+A **KILT DID** can expose services that allow external resources to be linked to the DID.
+**KILT credentials** represent one type of external resource.
 
-We will keep adding code below what we just added.
-The code snippet retrieves the services exposed by the DID we found for `john_doe`:
+You can retrieve the **services** attached to John Doe's DID and see if they link to any public credentials to **query** and **verify**.
+
+Add the following code after the code you added in the previous step but before the `await Kilt.disconnect()`. It retrieves the services exposed by the DID found for `john_doe`:
```
Comment (Dudleyneedham) [inline docs/develop/01_sdk/01_quickstart.md]:
```suggestion
Add the following code after the code you added in the previous step but before the `await Kilt.disconnect()`.
It retrieves the services exposed by the DID found for `john_doe`:
```

File: code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts [hunk 8]
```diff
@@ -10,6 +10,6 @@ export async function main(
   } = await axios.get<Kilt.KiltPublishedCredentialCollectionV1>(
     endpoints[0].serviceEndpoint[0]
   )
-
+  console.log(`Credentials: ${credential}`)
```
Comment (Dudleyneedham) [inline code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts]:
```suggestion
  console.log(`Credentials: ${JSON.stringify(credential, null, 2)}`)
```

Comment (Dudleyneedham) [reply code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts]: Inside 06 we also log out a credential. Do we want to do it twice? I don't mind since they are learning.

What if we fetch all the available credentials and display them or we could take the claim details in the last log when we state  it is valid and has been attested.

**Review by Dudleyneedham — APPROVED** [review]
LGTM, some minor comments.

Took a few seconds to run through the projects.

File: code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts (hunk 8 above)
Comment (ChrisChinchilla) [reply code_examples/sdk_examples/src/core_features/getting_started/05_fetch_endpoint_data.ts]: @Dudleyneedham I think for now, we just remove the log in 06 and just keep the output of the attester value and that it was valid, it seems enough and emphasis the flow more.

File: code_examples/sdk_examples/src/core_features/getting_started/06_verify_credential.ts [hunk 9]
```diff
@@ -2,17 +2,15 @@ import * as Kilt from '@kiltprotocol/sdk-js'
...
+      await Kilt.Credential.verifyCredential(credential)
 
     // Verify that the credential is not revoked. Exception caught by the catch {} block below.
     if (revoked) {
       throw new Error('The credential has been revoked, hence it is not valid.')
     }
     console.log(
-      `John Doe's credential is valid and has been attested by ${attester}!`,
-      JSON.stringify(credential, null, 2)
+      `John Doe's credential is valid and has been attested by ${attester}!`
```
Comment (ChrisChinchilla) [inline code_examples/sdk_examples/src/core_features/getting_started/06_verify_credential.ts:13]: @Dudleyneedham Here
